/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se;

public class AppCLI  {

    public static void main(String[] args) {
        System.out.println("Books in the DB ");
    }

}